/// GENERATED BY mvc_gen.dart
/// DO NOT EDIT BY HAND!

class AppRoutes {
  static const String welcomeView = '/welcome';
  static const String introductionView = '/introduction';
  static const String shortenView = '/shorten';

  static const initialView = welcomeView;
}